openapi: 3.2.0
info:
  version: 0.1.0
  title: Core Capabilities API
  description: The Core API provides essential building blocks that empower businesses to embed financial services into their applications.
  contact:
    name: Uphold API Team
    email: developers@uphold.com
    url: https://developer.uphold.com
servers:
- url: https://api.enterprise.sandbox.uphold.com
  description: Sandbox
- url: https://api.enterprise.uphold.com
  description: Production
security:
- OAuth2: []
tags:
- name: Capabilities
  description: User capabilities.
paths:
  /core/capabilities:
    get:
      operationId: core.list-capabilities
      summary: List capabilities
      description: List user capabilities.
      tags:
      - Capabilities
      x-uphold:
        security:
          OAuth2:
            subjects:
            - user:individual
            - user:business
      security:
      - OAuth2:
        - core.capabilities:read
      parameters:
      - $ref: '#/components/parameters/x-on-behalf-of'
      - $ref: '#/components/parameters/x-uphold-user-ip'
      - $ref: '#/components/parameters/x-uphold-user-agent'
      - $ref: '#/components/parameters/x-uphold-user-origin'
      - $ref: '#/components/parameters/x-uphold-user-country'
      - $ref: '#/components/parameters/x-uphold-user-subdivision'
      - $ref: '#/components/parameters/x-uphold-user-city'
      responses:
        '200':
          $ref: '#/components/responses/list-capabilities-response'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '429':
          $ref: '#/components/responses/too-many-requests'
  /core/capabilities/{capability}:
    get:
      operationId: core.get-capability
      summary: Get capability
      description: Retrieve a user capability by code.
      tags:
      - Capabilities
      x-uphold:
        security:
          OAuth2:
            subjects:
            - user:individual
            - user:business
      security:
      - OAuth2:
        - core.capabilities:read
      parameters:
      - $ref: '#/components/parameters/capability-code'
      - $ref: '#/components/parameters/x-on-behalf-of'
      - $ref: '#/components/parameters/x-uphold-user-ip'
      - $ref: '#/components/parameters/x-uphold-user-agent'
      - $ref: '#/components/parameters/x-uphold-user-origin'
      - $ref: '#/components/parameters/x-uphold-user-country'
      - $ref: '#/components/parameters/x-uphold-user-subdivision'
      - $ref: '#/components/parameters/x-uphold-user-city'
      responses:
        '200':
          $ref: '#/components/responses/get-capability-response'
        '400':
          $ref: '#/components/responses/bad-request'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '429':
          $ref: '#/components/responses/too-many-requests'
components:
  parameters:
    x-on-behalf-of:
      name: X-On-Behalf-Of
      description: The subject on whose behalf the operation is being performed.
      in: header
      schema:
        type: string
        pattern: ^(user|client)\s[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$
      examples:
        User Identifier:
          value: user cd21b26d-35d2-408a-9201-b8fdbef7a604
        Client Identifier:
          value: client 3fa85f64-5717-4562-b3fc-2c963f66afa6
    capability-code:
      name: capability
      description: The capability code.
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/capability-code'
      examples:
        Trades:
          value: trades
    x-uphold-user-country:
      name: X-Uphold-User-Country
      description: Contains the code of the country of the end user that is requesting the operation.
      in: header
      schema:
        $ref: '#/components/schemas/country-code-for-request'
      examples:
        User Country:
          value: US
    x-uphold-user-agent:
      name: X-Uphold-User-Agent
      description: Contains the user agent of the end user that is requesting the operation.
      in: header
      schema:
        $ref: '#/components/schemas/string-no-edge-spaces'
      examples:
        User Agent:
          value: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
    x-uphold-user-city:
      name: X-Uphold-User-City
      description: Contains the name of the city of the end user that is requesting the operation.
      in: header
      schema:
        $ref: '#/components/schemas/string-no-edge-spaces'
      examples:
        User City:
          value: San Francisco
    x-uphold-user-ip:
      name: X-Uphold-User-Ip
      description: Contains the IP of the end user that is requesting the operation.
      in: header
      schema:
        oneOf:
        - title: IPv4
          type: string
          format: ipv4
        - title: IPv6
          type: string
          format: ipv6
      examples:
        User Ip:
          value: 47.174.97.164
    x-uphold-user-origin:
      name: X-Uphold-User-Origin
      description: Contains the origin of the request made by the end user.
      in: header
      schema:
        $ref: '#/components/schemas/string-no-edge-spaces'
      examples:
        Origin:
          value: https://uphold.com
    x-uphold-user-subdivision:
      name: X-Uphold-User-Subdivision
      description: Contains the code of the subdivision of the end user that is requesting the operation.
      in: header
      schema:
        $ref: '#/components/schemas/subdivision-code-for-request'
      examples:
        User Subdivision:
          value: US-CA
  responses:
    forbidden:
      description: Forbidden.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
          examples:
            Token Insufficient Scopes:
              value:
                code: token_insufficient_scopes
                message: Authorization failed due to insufficient scopes
                details:
                  security:
                  - scheme: OAuth
                    schemeScopes:
                    - required:scope_1
                    - required:scope_2
                    tokenScopes:
                    - token:scope
      headers:
        x-uphold-request-id:
          description: A unique identifier for the request that can be shared with Uphold for troubleshooting purposes.
          required: true
          schema:
            type: string
            format: uuid
          examples:
            Request ID:
              value: 9092ee4d-f0fb-42e9-8787-b668dbcec531
    too-many-requests:
      description: Too Many Requests.
      headers:
        Retry-After:
          description: The number of seconds to wait before making a new request.
          schema:
            type: integer
            format: int32
          examples:
            Retry After:
              value: 60
        x-uphold-request-id:
          description: A unique identifier for the request that can be shared with Uphold for troubleshooting purposes.
          required: true
          schema:
            type: string
            format: uuid
          examples:
            Request ID:
              value: 9092ee4d-f0fb-42e9-8787-b668dbcec531
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
          examples:
            Too Many Requests:
              value:
                code: too_many_requests
                message: Try again later
    get-capability-response:
      description: Capability retrieved.
      content:
        application/json:
          schema:
            type: object
            properties:
              capability:
                $ref: '#/components/schemas/capability'
            required:
            - capability
          examples:
            Capability Retrieved:
              value:
                capability:
                  code: trades
                  name: Trades
                  enabled: true
                  requirements:
                  - user-must-submit-identity
                  - user-must-submit-proof-of-address
                  restrictions: []
      headers:
        x-uphold-request-id:
          description: A unique identifier for the request that can be shared with Uphold for troubleshooting purposes.
          required: true
          schema:
            type: string
            format: uuid
          examples:
            Request ID:
              value: 9092ee4d-f0fb-42e9-8787-b668dbcec531
    bad-request:
      description: Bad Request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
          examples:
            Invalid Request:
              value:
                code: request_invalid
                message: The request has missing or invalid parameters
                details:
                  context: <context>
                  violations:
                  - property: <property>
                    rule: required
                  - property: <property>
                    rule: type
                    ruleParams:
                      type: string
      headers:
        x-uphold-request-id:
          description: A unique identifier for the request that can be shared with Uphold for troubleshooting purposes.
          required: true
          schema:
            type: string
            format: uuid
          examples:
            Request ID:
              value: 9092ee4d-f0fb-42e9-8787-b668dbcec531
    unauthorized:
      description: Unauthorized.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
          examples:
            Token Expired:
              value:
                code: token_expired
                message: The access token has expired
            Token Invalid:
              value:
                code: token_invalid
                message: The access token is invalid
            Token Revoked:
              value:
                code: token_revoked
                message: The access token has been revoked
      headers:
        x-uphold-request-id:
          description: A unique identifier for the request that can be shared with Uphold for troubleshooting purposes.
          required: true
          schema:
            type: string
            format: uuid
          examples:
            Request ID:
              value: 9092ee4d-f0fb-42e9-8787-b668dbcec531
    list-capabilities-response:
      description: Capabilities retrieved.
      content:
        application/json:
          schema:
            type: object
            properties:
              capabilities:
                type: array
                items:
                  $ref: '#/components/schemas/capability'
            required:
            - capabilities
          examples:
            Capabilities Retrieved:
              value:
                capabilities:
                - code: bank-deposits
                  name: Deposit from bank
                  enabled: true
                  requirements:
                  - user-must-submit-identity
                  - user-must-submit-customer-due-diligence
                  - user-must-submit-proof-of-address
                  restrictions: []
                - code: crypto-deposits
                  name: Deposit from crypto networks
                  enabled: true
                  requirements:
                  - user-must-submit-identity
                  - user-must-submit-customer-due-diligence
                  - user-must-submit-proof-of-address
                  restrictions: []
                - code: deposits
                  name: Deposit from other methods
                  enabled: true
                  requirements:
                  - user-must-submit-identity
                  - user-must-submit-customer-due-diligence
                  - user-must-submit-proof-of-address
                  restrictions: []
                - code: receives
                  name: Receives
                  enabled: true
                  requirements:
                  - user-must-submit-identity
                  - user-must-submit-customer-due-diligence
                  - user-must-submit-proof-of-address
                  restrictions: []
                - code: sends
                  name: Sends
                  enabled: true
                  requirements:
                  - user-must-submit-identity
                  - user-must-submit-customer-due-diligence
                  - user-must-submit-proof-of-address
                  restrictions: []
                - code: trades
                  name: Trades
                  enabled: true
                  requirements:
                  - user-must-submit-identity
                  - user-must-submit-customer-due-diligence
                  - user-must-submit-proof-of-address
                  restrictions: []
                - code: bank-withdrawals
                  name: Withdraw to bank
                  enabled: true
                  requirements:
                  - user-must-submit-identity
                  - user-must-submit-customer-due-diligence
                  - user-must-submit-proof-of-address
                  restrictions: []
                - code: card-withdrawals
                  name: Withdraw to credit card
                  enabled: true
                  requirements:
                  - user-must-submit-identity
                  - user-must-submit-customer-due-diligence
                  - user-must-submit-proof-of-address
                  restrictions: []
                - code: crypto-withdrawals
                  name: Withdraw to crypto networks
                  enabled: true
                  requirements:
                  - user-must-submit-identity
                  - user-must-submit-customer-due-diligence
                  - user-must-submit-proof-of-address
                  restrictions: []
                - code: cards
                  name: Cards
                  enabled: true
                  requirements:
                  - user-must-submit-identity
                  - user-must-delete-card
                  - user-must-submit-residential-address
                  restrictions: []
                - code: unique-account-number-viban
                  name: Unique Account Number (Virtual IBAN)
                  enabled: true
                  requirements:
                  - user-must-submit-identity
                  - user-must-accept-unique-account-number-viban-terms-of-service
                  - user-must-submit-residential-address
                  restrictions: []
      headers:
        x-uphold-request-id:
          description: A unique identifier for the request that can be shared with Uphold for troubleshooting purposes.
          required: true
          schema:
            type: string
            format: uuid
          examples:
            Request ID:
              value: 9092ee4d-f0fb-42e9-8787-b668dbcec531
  schemas:
    feedback:
      description: A feedback message with a code and human-readable description.
      type: object
      properties:
        code:
          description: A short string with a brief explanation about the code reported.
          type: string
        message:
          description: A human-readable message providing more details.
          type: string
        details:
          description: Additional information about the feedback reported.
          type: object
          additionalProperties: true
      required:
      - code
      - message
    string-no-edge-spaces:
      type: string
      pattern: ^\S.*\S$|^\S$
    error:
      description: The error information.
      allOf:
      - $ref: '#/components/schemas/feedback'
    capability-code:
      description: The code of the capability.
      type: string
      enum:
      - crypto-withdrawals
      - card-withdrawals
      - bank-withdrawals
      - apple-pay-withdrawals
      - paypal-withdrawals
      - venmo-withdrawals
      - crypto-deposits
      - bank-deposits
      - deposits
      - receives
      - sends
      - trades
      - cards
      - apple-pay
      - paypal
      - venmo
      - unique-account-number-viban
    capability:
      type: object
      properties:
        code:
          $ref: '#/components/schemas/capability-code'
        name:
          description: The name of the capability.
          type: string
        enabled:
          description: Whether the capability is enabled. If this is false, then there's at least one restrictions active.
          type: boolean
        requirements:
          description: The missing requirements for this capability to be fulfilled.
          type: array
          items:
            type: string
            enum:
            - user-must-submit-crypto-risk-assessment-form
            - user-must-submit-self-categorization-form
            - user-must-submit-residential-address
            - user-must-submit-customer-due-diligence
            - user-must-submit-enhanced-due-diligence
            - user-must-wait-for-the-email-cooldown-period-to-expire
            - user-must-submit-full-name
            - user-must-submit-identity
            - user-must-submit-identity-via-physical-document
            - user-must-submit-phone-number
            - user-must-submit-proof-of-address
            - user-must-submit-tax-details
            - user-must-submit-tax-identification-number
            - user-must-submit-w9-form
            - user-must-accept-unique-account-number-viban-terms-of-service
            - user-must-delete-card
        restrictions:
          description: The restrictions that are causing this capability to be disabled.
          type: array
          items:
            type: string
            enum:
            - crypto-risk-assessment-form-not-valid
            - financial-promotion-cooldown-running
            - phone-country-not-supported
            - self-categorization-statement-form-not-valid
            - temporarily-disabled
            - user-residential-address-not-valid
            - user-cannot-receive-funds
            - user-country-not-supported
            - user-enhanced-due-diligence-not-valid
            - user-identity-not-valid
            - user-proof-of-address-not-valid
            - user-screening-running
            - user-state-not-supported
            - user-status-not-valid
            - user-type-not-supported
            - user-w9-form-not-valid
            - user-unique-card-limit-reached
      required:
      - code
      - name
      - enabled
      - requirements
      - restrictions
    subdivision-code-for-request:
      type: string
      pattern: ^[A-Z]{2}-[A-Z0-9]{1,3}$
    country-code-for-request:
      type: string
      pattern: ^[A-Z]{2}$
  securitySchemes:
    OAuth2:
      type: oauth2
      description: OAuth 2.0 authentication.
      flows:
        clientCredentials:
          tokenUrl: /core/oauth2/token
          scopes:
            core.users:act-on-behalf-of: Grants access to act on behalf of a user
            core.users:create: Grants access to create users
            core.users:read: Grants access to view users
            core.users:delete: Grants access to delete users
            core.users.metadata:read: Grants access to view user metadata
            core.users.metadata:write: Grants access to modify user metadata
            core.kyc:read: Grants access to view KYC processes
            core.kyc.profile:update: Grants access to update profile KYC process
            core.kyc.address:update: Grants access to update address KYC process
            core.kyc.email:update: Grants access to update email KYC process
            core.kyc.phone:update: Grants access to update phone KYC process
            core.kyc.identity:update: Grants access to update identity KYC process
            core.kyc.proof-of-address:update: Grants access to update proof-of-address KYC process
            core.kyc.customer-due-diligence:update: Grants access to update customer due diligence KYC process
            core.kyc.enhanced-due-diligence:update: Grants access to update enhanced due diligence KYC process
            core.kyc.crypto-risk-assessment:update: Grants access to update crypto risk assessment KYC process
            core.kyc.self-categorization-statement:update: Grants access to update self-categorization statement KYC process
            core.kyc.tax-details:update: Grants access to update tax details KYC process
            core.capabilities:read: Grants access to view user capabilities
            core.terms-of-service:read: Grants access to view terms of service
            core.terms-of-service:accept: Grants access to accept terms of service
            core.files:create: Grants access to create files
            core.files:read: Grants access to view files
            core.files.metadata:read: Grants access to view files metadata
            core.files.metadata:write: Grants access to modify files metadata
            core.accounts:create: Grants access to create accounts
            core.accounts:read: Grants access to view accounts
            core.accounts:update: Grants access to update accounts
            core.accounts:archive: Grants access to archive accounts
            core.accounts:deposit-method: Grants access to deposit method needed for depositing into accounts
            core.accounts:use-test-helpers: Grants access to test helpers of accounts
            core.accounts.metadata:read: Grants access to view accounts metadata
            core.accounts.metadata:write: Grants access to modify accounts metadata
            core.assets:use-test-helpers: Grants access to test helpers of assets
            core.external-accounts:create: Grants access to create external accounts
            core.external-accounts:read: Grants access to view external accounts
            core.external-accounts:update: Grants access to update external accounts
            core.external-accounts:delete: Grants access to delete external accounts
            core.external-accounts.metadata:read: Grants access to view external accounts metadata
            core.external-accounts.metadata:write: Grants access to modify external accounts metadata
            core.transactions:create: Grants access to commit quotes
            core.transactions:read: Grants access to view transactions
            core.transactions.metadata:read: Grants access to view transactions metadata
            core.transactions.metadata:write: Grants access to modify transactions metadata
            core.transactions.requests-for-information:read: Grants access to view transactions requests for information
            core.transactions.requests-for-information:update: Grants access to update transactions requests for information
            core.portfolio:read: Grants access to view portfolio overview, performance, and historical balance
            core.statements:read: Grants access to read statements
            core.webhooks:management-link: Grants access to create webhook management links
